// <auto-generated />
using System;
using FinanceService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceService.Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123163406_InitialCreateSqlite_1")]
    partial class InitialCreateSqlite_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FinanceService.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_addresses");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_addresses_created_at");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.AuthDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_salt");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_auth_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_auth_details_created_at");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("i_x_auth_details_provider_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_auth_details_user_id");

                    b.ToTable("auth_details");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.BankAccountDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_name");

                    b.Property<Guid>("BankType")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurrencyCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCountable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_countable");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_bank_account_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_bank_account_details_created_at");

                    b.ToTable("bank_account_details");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlternateEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alternate_email");

                    b.Property<string>("AlternatePhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alternate_phone_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MobileCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("mobile_code");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_contacts");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_contacts_created_at");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_name");

                    b.Property<Guid>("AccountType")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_type");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<long>("InitialBalance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_balance");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_financial_accounts");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("i_x_financial_accounts_bank_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_financial_accounts_created_at");

                    b.ToTable("financial_accounts");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.FinancialStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurrencyCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TaxYearId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_year_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_financial_statements");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_financial_statements_created_at");

                    b.HasIndex("TaxYearId")
                        .HasDatabaseName("i_x_financial_statements_tax_year_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_financial_statements_user_id");

                    b.ToTable("financial_statements");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.FinancialStatementAccountMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_account_id");

                    b.Property<Guid>("FinancialStatementId")
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_statement_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_financial_statement_account_mappings");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_financial_statement_account_mappings_created_at");

                    b.HasIndex("FinancialAccountId")
                        .HasDatabaseName("i_x_financial_statement_account_mappings_financial_account_id");

                    b.HasIndex("FinancialStatementId")
                        .HasDatabaseName("i_x_financial_statement_account_mappings_financial_statement_id");

                    b.ToTable("financial_statement_account_mappings");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.ProviderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderSubId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_sub_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_provider_details");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_provider_details_created_at");

                    b.ToTable("provider_details");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_refresh_tokens_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.TaxYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("p_k_tax_years");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tax_years_created_at");

                    b.ToTable("tax_years");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("picture_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.UserBankMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BankAccountDetailId")
                        .HasColumnType("TEXT")
                        .HasColumnName("bank_account_detail_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_bank_mappings");

                    b.HasIndex("BankAccountDetailId")
                        .HasDatabaseName("i_x_user_bank_mappings_bank_account_detail_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_bank_mappings_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_bank_mappings_user_id");

                    b.ToTable("user_bank_mappings");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.UserFinancialStatementMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FinancialStatementId")
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_statement_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_financial_statement_mappings");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_financial_statement_mappings_created_at");

                    b.HasIndex("FinancialStatementId")
                        .HasDatabaseName("i_x_user_financial_statement_mappings_financial_statement_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_financial_statement_mappings_user_id");

                    b.ToTable("user_financial_statement_mappings");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.UserLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_locked");

                    b.Property<DateTime>("LastFailedAttempt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_failed_attempt");

                    b.Property<long>("LockCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lock_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_locks");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_locks_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_locks_user_id");

                    b.ToTable("user_locks");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.AuthDetail", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.ProviderDetail", "ProviderDetail")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .HasConstraintName("f_k_auth_details__provider_details_provider_id");

                    b.HasOne("FinanceService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_auth_details__users_user_id");

                    b.Navigation("ProviderDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.FinancialAccount", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.BankAccountDetail", "BankAccountDetail")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_financial_accounts_bank_account_details_bank_account_id");

                    b.Navigation("BankAccountDetail");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.FinancialStatement", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.TaxYear", "TaxYear")
                        .WithMany()
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_financial_statements__tax_years_tax_year_id");

                    b.HasOne("FinanceService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_financial_statements__users_user_id");

                    b.Navigation("TaxYear");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.FinancialStatementAccountMapping", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_financial_statement_account_mappings_financial_accounts_financial_account_id");

                    b.HasOne("FinanceService.Domain.Models.FinancialStatement", "FinancialStatement")
                        .WithMany()
                        .HasForeignKey("FinancialStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_financial_statement_account_mappings_financial_statements_financial_statement_id");

                    b.Navigation("FinancialAccount");

                    b.Navigation("FinancialStatement");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_refresh_tokens__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.UserBankMapping", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.BankAccountDetail", "BankAccountDetail")
                        .WithMany()
                        .HasForeignKey("BankAccountDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_bank_mappings_bank_account_details_bank_account_detail_id");

                    b.HasOne("FinanceService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_bank_mappings_users_user_id");

                    b.Navigation("BankAccountDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.UserFinancialStatementMapping", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.FinancialStatement", "FinancialStatement")
                        .WithMany()
                        .HasForeignKey("FinancialStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_financial_statement_mappings_financial_statements_financial_statement_id");

                    b.HasOne("FinanceService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_financial_statement_mappings_users_user_id");

                    b.Navigation("FinancialStatement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceService.Domain.Models.UserLock", b =>
                {
                    b.HasOne("FinanceService.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_locks_users_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
